#!/usr/bin/env bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR/.." || exit

./mvnw clean package
rm -rf ./target/keycloak
mkdir -p ./target/keycloak/providers
cp ./target/keycloak-role-attribute-mapper-*.jar ./target/keycloak/providers
